name: DingTalk Notification

on:
  push:
    branches:
      - master

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get commit info
        id: commit
        uses: actions/github-script@v6
        with:
          script: |
            const commit = context.payload.head_commit;
            const author = commit.author.name;
            const repo = context.repo.repo;
            return { author, repo };

      - name: Send DingTalk notification
        uses: wangzaiplus/dingtalk-action@v1.0.0
        with:
          dingtalk_token: ${{ secrets.DINGTALK_TOKEN }}
          dingtalk_secret: ${{ secrets.DINGTALK_SECRET }}
          msgtype: text
          msg: |
            【${{ steps.commit.outputs.author }}】在【${{ steps.commit.outputs.repo }}】仓库里提交了，大家快去看呀
